# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
# 倒入numpy as np
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
# 打印numpy版本和config
print(np.__version__)
print(np.__config__)

1.15.0
<module 'numpy.__config__' from '/home/yinjian/anaconda3/lib/python3.6/site-packages/numpy/__config__.py'>


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
# 创建一个向量大小为10的数组
a = np.empty(10)
a

array([0.00000000e+000, 6.91849302e-310, 6.91849302e-310, 6.91849302e-310,
       6.32404027e-322, 3.95252517e-322, 0.00000000e+000, 6.91850170e-310,
       6.91850170e-310, 6.91850170e-310])

#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
# 找到array的内存大小
a = np.zeros(10)
a.size*a.itemsize

80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
# np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
# 创建一个长度为10的数组，第5个数组为1
a = np.empty(10)
a[4] = 1
a

array([1.13516632e-250, 1.13516632e-250, 1.13516632e-250, 1.13516632e-250,
       1.00000000e+000, 1.13516632e-250, 1.13516632e-250, 1.13516632e-250,
       1.13516632e-250, 1.13516632e-250])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
# 创建一个数组从10到49
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [8]:
# 反转一个向量
a = a[::-1]
a

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
# 创建一个3*3的大小的数组0～8
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [10]:
# 找到非0元素的索引
a = np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
# 创建一个3*3的对角阵
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
# 创建3*3*3的随机数组
a = np.random.random((3,3))
# a = np.random.rand(3,3)
a

array([[0.42636948, 0.82081255, 0.55134779],
       [0.80752272, 0.14608029, 0.24856639],
       [0.16950785, 0.01222346, 0.80010313]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
# 创建一个10*10的随机数组，找到最大的值，最小的值
a = np.random.rand(10,10)
print(a)
print(np.min(a), np.max(a))

[[0.43775621 0.44398849 0.10244562 0.18844243 0.1524023  0.79719387
  0.48072398 0.98588412 0.4416954  0.68704327]
 [0.73652562 0.15639098 0.12200266 0.95506607 0.48173257 0.9366238
  0.08547101 0.15989099 0.99028274 0.65518661]
 [0.72169226 0.72909259 0.40763271 0.59500573 0.95694498 0.23901926
  0.64283246 0.35677554 0.26802848 0.4635398 ]
 [0.45391671 0.29457607 0.16574408 0.8342713  0.68321902 0.44647181
  0.28111001 0.13857363 0.99014652 0.05979357]
 [0.4579076  0.67008387 0.38238359 0.98737369 0.3081576  0.35262755
  0.13185377 0.73454284 0.12719324 0.74500307]
 [0.04610766 0.71620077 0.48964137 0.93148067 0.01809216 0.46694139
  0.03117692 0.1422673  0.50229068 0.9796286 ]
 [0.30178428 0.15674841 0.26915045 0.34735685 0.65896637 0.95220134
  0.29239683 0.70275379 0.24280565 0.707938  ]
 [0.99676888 0.69319505 0.60404721 0.53535381 0.56422085 0.70248113
  0.86536204 0.49556324 0.58896075 0.44906192]
 [0.73052836 0.54106855 0.41837192 0.91850695 0.84813532 0.53637444
  0.11737386 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
# 创建一个大小为30的随机数组，求均值
a = np.random.rand(30)
a.mean()

0.48611439170371834

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
# 创建一个2d数组，1是边界，里面是0
a = np.zeros((10,10))
a[[0,-1],:] = 1
a[:, [0,-1]] = 1
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
# 给一个存在的数组添加一个边框fill 0
a = np.ones((5,5))
# np.pad?
a = np.pad(a, pad_width=1, mode='constant')
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
# 创建5*5矩阵，1，2，3，4低于对角线
a = np.zeros((5,5))
a[[1,2,3,4],[0,1,2,3]] = 1,2,3,4
a

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
# 创建一个8*8的矩阵 0，1间隔
a = np.zeros((8,8))
# a[::2,1::2] = 1
# a[1::2, 0::2] = 1
b = a[::2,1::2]
b[:] = 1
c = a[1::2, 0::2]
c[:] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
# 考虑一个6*7*8的数组，第100个元素的(x,y,z)索引是多少？
# (1,5,3)
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
# 用函数创建一个8*8的矩阵 0，1间隔
a = np.tile(np.array([[0,1],[1,0]]), (4,4))
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
# 归一化一个5*5的矩阵
a = np.random.random((5,5))
a - a.mean() / a.std()

array([[-1.78712513, -1.61395796, -1.70767147, -1.62463712, -1.65529929],
       [-2.00682561, -2.13320907, -1.2825138 , -1.45834852, -1.59937234],
       [-1.26450929, -1.82273196, -1.73440445, -1.78618914, -1.43220583],
       [-2.0670171 , -1.49855744, -2.00788789, -1.72300344, -1.58216696],
       [-1.85093445, -1.50740946, -1.83622768, -1.5496861 , -1.79713782]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
# 创建一个描述颜色的数据，4个无符号的数据
color = np.dtype([("r", np.uint, 1),
                 ("g", np.uint, 1),
                 ("b", np.uint, 1),
                 ("a", np.uint, 1)])
color

dtype([('r', '<u8'), ('g', '<u8'), ('b', '<u8'), ('a', '<u8')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
# 5*3 * 3*2 矩阵乘法
a = np.arange(15).reshape((5,3))
b = np.arange(6).reshape((3,2))
np.dot(a, b) # python3.5 a@b

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
# 给定1D array，3-8的元素全部取负
a = np.arange(12)
a[(a >=3) & (a <=8)] *= -1
a

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
# 哪些是合法的
Z = np.arange(5)
print(Z)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z)

[0 1 2 3 4]
[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
np.array([np.nan]).astype(int).astype(float)

nan
0


/home/yinjian/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/home/yinjian/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [29]:
# 如何从远离0的方向取整（负数强制转换是不对的）
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))
Z

[-6. -2.  3. 10. -3.  4.  7. -6. -1. -3.]


array([-5.35235101, -1.64736205,  2.19695521,  9.98480322, -2.55363104,
        3.9155619 ,  6.23903544, -5.68756804, -0.44423147, -2.4825567 ])

#### 30. How to find common values between two arrays? (★☆☆)

In [30]:
# 怎样找到两个数组的公共部分
a = np.arange(12)
b = np.arange(1,13)
print(a,b)
np.intersect1d(a,b)

# np.unique  唯一元素
# np.intersect1d 交集
# np.union1d 并集

[ 0  1  2  3  4  5  6  7  8  9 10 11] [ 1  2  3  4  5  6  7  8  9 10 11 12]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [31]:
# 忽略所有的numpy警告

defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0
    print(Z)

[inf]


#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
np.emath.sqrt(-1), np.sqrt(-1)

/home/yinjian/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


(1j, nan)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [33]:
# 获得昨天，今天，明天的时间
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
yesterday, today, tomorrow

(numpy.datetime64('2019-07-28'),
 numpy.datetime64('2019-07-29'),
 numpy.datetime64('2019-07-30'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [35]:
# 怎样计算(a+b)*(-a/2) 对应元素操作，不copy
a = np.array

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [36]:
# 用5种方法提取随机数组的整数部分
a = np.random.uniform(0,10,10)
print(a)
print(np.floor(a))
print(np.ceil(a)-1)
print(a - a%1)
print(a.astype(np.int))
print(np.trunc(a))

[2.33769646 9.01817592 9.8617122  6.89190873 8.3254633  7.75227903
 2.85433529 4.24469079 4.02935536 2.86896978]
[2. 9. 9. 6. 8. 7. 2. 4. 4. 2.]
[2. 9. 9. 6. 8. 7. 2. 4. 4. 2.]
[2. 9. 9. 6. 8. 7. 2. 4. 4. 2.]
[2 9 9 6 8 7 2 4 4 2]
[2. 9. 9. 6. 8. 7. 2. 4. 4. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
# 新建一个5*5的array， 数值0~4随机
# a = np.random.randint()
# np.random.randint?
a = np.random.randint(0,5,size=(5,5))
a

array([[0, 4, 3, 2, 0],
       [3, 3, 3, 1, 4],
       [0, 4, 4, 1, 3],
       [0, 4, 3, 0, 3],
       [2, 0, 3, 1, 1]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [38]:
# 考虑一个生成器函数，构建10个整数，用他来建立array
def generate():
    for x in range(10):
        yield x
    
a = np.fromiter(generate(), dtype=float, count=-1)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [39]:
# 建立一个从0->1的size=0的数组，两端都包括

# np.linspace?
a = np.linspace(0,1,10)
a

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [40]:
# 建立一个随机数组，给他排序
a = np.random.random(10)
a.sort()
a

array([0.01347355, 0.07140876, 0.23530283, 0.45296411, 0.48762793,
       0.55965039, 0.75369734, 0.75669472, 0.87740955, 0.89244534])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [41]:
# 比np.sum求和更快的方式
a = np.arange(4)
np.add.reduce(a)

6

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [42]:
# 考虑两个随机数组a,b， 检查他们是否相等
a = np.random.random(12)
b = np.random.random(12)
a == b

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

#### 43. Make an array immutable (read-only) (★★☆)

In [43]:
# 建立一个只读数组
a = np.arange(10)
a.flags.writeable = False
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [44]:
# 考虑一个随机10*2矩阵代表笛卡尔坐标，转为极坐标
a = np.random.random((10,2))
# 只能数学计算
x, y = a[:,0], a[:,1]
r = np.sqrt(x**2 + y**2)
t = np.arctan2(y,x)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [45]:
# 创建一个10大小的随机矩阵，最大值替换为0
a = np.random.random(10)
print(a)
# a[a==a.max()] = 0
a[a.argmax()] = 0
a

[0.46566192 0.38505534 0.60901786 0.44993896 0.30076916 0.62488658
 0.70434487 0.3612143  0.29911045 0.31688552]


array([0.46566192, 0.38505534, 0.60901786, 0.44993896, 0.30076916,
       0.62488658, 0.        , 0.3612143 , 0.29911045, 0.31688552])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [46]:
# 创建一个结构化数组，其x和y坐标覆盖[0,1] x [0,1]区域

# Z = np.zeros((5,5), [('x',float),('y',float)])
# Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
#                              np.linspace(0,1,5))
# print(Z)

x, y = np.linspace(0,1,5), np.linspace(0,1,5)
X, Y = np.meshgrid(x, y)
X, Y
# print(x)
# print(y)

(array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ]]),
 array([[0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.25, 0.25, 0.25, 0.25, 0.25],
        [0.5 , 0.5 , 0.5 , 0.5 , 0.5 ],
        [0.75, 0.75, 0.75, 0.75, 0.75],
        [1.  , 1.  , 1.  , 1.  , 1.  ]]))

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [47]:
# 给定两个数组，X和Y，构造Cauchy矩阵C（Cij = 1 /（xi-yj））
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

# 广播
# X = X.reshape((-1,1))
# C = 1.0 / (X - Y) 
# print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [48]:
# 打印每个numpy标量类型的最小和最大可表示值
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [49]:
# 元素太多打印会省略，怎样打印array的所有值
np.set_printoptions(threshold=np.nan)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [50]:
# 如何在向量中找到最接近的值(给定标量)
a = np.arange(0, 100)
v = np.random.uniform(0,100) # 不包含右端点
a[np.argmin(np.abs(a-v))], v

(60, 60.370115781711796)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [51]:
# 创建表示位置和颜色的结构化数组
postion = np.dtype([('x', '<i8'), ('y', '<i8')])
color = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8)])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [52]:
# 考虑一个随机向量，其形状（100,2）代表坐标，找到各点之间的距离(100,100)
Z = np.random.random((10,2))
# print(Z)
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
# X, Y, X.shape
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
D

array([[0.        , 0.31744757, 0.13020867, 0.59722896, 0.48430818,
        0.63988919, 0.29710127, 0.30995702, 0.60671234, 0.40113376],
       [0.31744757, 0.        , 0.43953586, 0.85024001, 0.18990622,
        0.34544005, 0.31534959, 0.47024095, 0.43842007, 0.69372469],
       [0.13020867, 0.43953586, 0.        , 0.56532076, 0.59307073,
        0.76896604, 0.3331256 , 0.26689316, 0.73043107, 0.34242785],
       [0.59722896, 0.85024001, 0.56532076, 0.        , 1.03936354,
        1.06411247, 0.88653954, 0.82651512, 0.85387368, 0.23463841],
       [0.48430818, 0.18990622, 0.59307073, 1.03936354, 0.        ,
        0.31994439, 0.36279013, 0.54611657, 0.53458865, 0.87561978],
       [0.63988919, 0.34544005, 0.76896604, 1.06411247, 0.31994439,
        0.        , 0.64427265, 0.81230685, 0.30629226, 0.96197217],
       [0.29710127, 0.31534959, 0.3331256 , 0.88653954, 0.36279013,
        0.64427265, 0.        , 0.18520362, 0.7443936 , 0.67309386],
       [0.30995702, 0.47024095, 0.2668931

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [53]:
# 如何将32位float转32位整数
a = np.arange(10, dtype=np.float32)
a = a.astype(np.int32, copy=False)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [54]:
# 怎样读这样的file文件
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")

a = np.genfromtxt(s, delimiter=',', dtype=int)
a

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [55]:
# numpy数组的枚举相当于什么？
a = np.arange(9).reshape((3,3))
for index, value in np.ndenumerate(a):
    print(index, value)
    
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [56]:
# 生成通用的2D高斯类数组
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
G

array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [57]:
# 如何将p元素随机放置在2D数组中？
# np.random.choice(a, size, replace) 在a中采样出size大小的数组, replace=False 抽完后不放回去
# np.put(a, ind, v, mode='raise')
# a.flat(ind) = v (flat返回一个迭代器)
a = np.zeros((10,10))
np.put(a, ind=np.random.choice(range(100), 3, replace=False), v=1)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [58]:
# 减去每一行的均值
a = np.arange(12).reshape(3,4)
print(a)
print(a.mean(axis=-1))
a - a.mean(axis=-1).reshape((-1,1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1.5 5.5 9.5]


array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

#### 59. How to sort an array by the nth column? (★★☆)

In [59]:
# 如何按第n列对数组进行排序(按照第i列的大小，将数组按行排序)
a = np.random.randint(0,10,(3,3))  # [low ,high)
print(a)
print(a[:,1])
print(a[:,1].argsort())
a[a[:,1].argsort()]

[[0 9 5]
 [5 7 3]
 [7 0 3]]
[9 7 0]
[2 1 0]


array([[7, 0, 3],
       [5, 7, 3],
       [0, 9, 5]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [60]:
# 如何判断给定的2D数组是否具有0列
# np.any 有一个元素为True，即为True，(注负数，和NaN(不是一个数)， 正无穷，负无穷都是True，只有0和False为False)
a = np.random.randint(0,3,(3,10))
print(a)
print(~a.any(axis=0))

[[0 2 0 0 0 1 1 2 1 0]
 [0 2 0 2 1 2 2 2 1 1]
 [1 0 2 2 2 0 0 1 2 1]]
[False False False False False False False False False False]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [61]:
# 从一个给定的数组找到最接近的数值
a = np.random.uniform(0,1,10)
print(a)
z = 0.5
a[np.abs(a-z).argmin()]

[0.61899673 0.26329217 0.52418361 0.04333855 0.99545738 0.62217804
 0.91217535 0.54345842 0.77462395 0.2053565 ]


0.5241836080526483

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [62]:
# 考虑两个形状为（1,3）和（3,1）的数组，如何使用迭代器计算它们的总和？
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])
# print(A+B)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [63]:
# 创建一个数组类，有一个名称属性
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [64]:
# 考虑一个给定的向量，如何为每个由第二个向量索引的元素添加1（小心重复索引）？
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
print(Z)
print(I)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 8 4 0 3 0 7 1 6 0 3 9 6 9 5 5 5 7 3]
[4. 2. 1. 4. 2. 6. 3. 3. 2. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [65]:
# 如何基于索引列表（I）将向量（X）的元素累积到数组（F）
# np.bincount(i,x) ans[i[j]] += x[j]
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
F

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [66]:
# 计算一张图有多少种颜色，每个像素点的颜色计算是 r*256*256 + g*256 + b
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte) # 创造出一张随机图片
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F1 = I[...,0]*(256*256) + I[...,1]*256 +I[...,2] # I[:,:,0] * 256*256
F2 = I[:,:,0]*(256*256) + I[:,:,1] * 256 + I[:,:,2]
n = len(np.unique(F1))
print(n, len(np.unique(F2)))

8 8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [67]:
# 考虑四维数组，如何一次得到最后两个轴的总和
# a.sum(axis=-1).sum(axis=-1)
a = np.random.randint(0,2,(4,4,2,2))
a.sum(axis=(-2,-1))

array([[3, 2, 2, 3],
       [1, 1, 2, 2],
       [2, 2, 1, 2],
       [0, 3, 1, 2]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [68]:
# 考虑一维向量D，如何使用描述子集索引的相同大小的向量S来计算D的子集的均值


#### 69. How to get the diagonal of a dot product? (★★★)

In [69]:
# 怎样获得矩阵相乘的对角线
a = np.random.uniform(0,1,(5,5))
b = np.random.uniform(0,1,(5,5))

np.diag(np.dot(a,b))

array([1.47527005, 1.18226179, 0.58176158, 0.94465783, 1.11021482])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [70]:
#考虑向量[1,2,3,4,5]，如何构建一个新的向量，在每个值之间插入3个连续的零？
a = np.array([1,2,3,4,5])
b = np.zeros(len(a) + (len(a)-1)*3)
b[::4] = a
b

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [71]:
# 考虑一个维度数组（5,5,3），如何将它乘以一个带维数的数组（5,5）
a = np.ones((5,5,3))
b = 2*np.ones((5,5))
print(a*b[:,:, np.newaxis])

print(a * b[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [72]:
# 如何交换数组的两行？
a = np.arange(12).reshape((3,4))
print(a)
a[[0,1]] = a[[1,0]]
a

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [73]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 22) ( 1, 53) ( 3, 13) ( 3, 89) (11, 32) (11, 33) (11, 75) (11, 94)
 (13, 89) (21, 28) (21, 79) (22, 53) (28, 79) (32, 33) (39, 49) (39, 64)
 (40, 55) (40, 71) (49, 64) (52, 63) (52, 76) (55, 71) (63, 76) (67, 86)
 (67, 95) (75, 84) (75, 94) (75, 98) (84, 98) (86, 95)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [74]:
# np.bincount(a) = c ，给定c 找到a
c = np.bincount([1,1,2,3,4,4,6])
a = np.repeat(np.arange(len(c)), c)
print(a)
np.bincount(a)

[1 1 2 3 4 4 6]


array([0, 2, 1, 1, 2, 0, 1])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [75]:
# 如何使用数组上的滑动窗口计算平均值
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [76]:
# 考虑一维数组Z，构建一个二维数组，其第一行为（Z [0]，Z [1]，Z [2]），每个后续行移1（最后一行应为（Z [-3]，Z[-2]，Z[-1]）
from numpy.lib import stride_tricks

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [77]:
# 如何否定布尔值，或改变浮点位置的符号？
Z = np.random.randint(0,2,100)
print(Z)
np.logical_not(Z, out=Z)
print(Z)

Z = np.random.uniform(-1.0,1.0,100)
print(Z)
np.negative(Z, out=Z)
print(Z)

[0 0 0 1 0 1 0 0 0 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 1 1 1 0 0
 0 1 0 1 1 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 1 1 1 1 1 0 1 0 0 1 0
 1 0 0 1 0 0 0 1 0 1 1 1 1 0 0 0 1 0 1 0 0 0 1 0 1 1]
[1 1 1 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 0 0 0 1 1
 1 0 1 0 0 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 0 0 0 0 0 0 1 0 1 1 0 1
 0 1 1 0 1 1 1 0 1 0 0 0 0 1 1 1 0 1 0 1 1 1 0 1 0 0]
[ 0.16282199  0.85591167  0.81749276 -0.60051203  0.74659768 -0.72791657
 -0.91884893  0.59177796  0.56856662 -0.52231731  0.64612662 -0.7661667
  0.81518546 -0.61882489  0.72381765  0.85092414  0.54774144  0.22094413
 -0.42756702 -0.38449542  0.96880178  0.31921137 -0.2147435  -0.76651439
  0.11314251 -0.08114659  0.12595132 -0.43430712  0.06281291 -0.36346984
  0.16083739  0.19211863 -0.28814076  0.56946943 -0.56805107 -0.91200786
 -0.8526279  -0.72875193 -0.38203084 -0.93242678  0.07433245 -0.26784799
 -0.10844954 -0.39487728  0.9289827  -0.0149122   0.82447825 -0.28874795
  0.08196

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [78]:
# 考虑2组点P0，P1描述线（2d）和点p，如何计算从p到每条线i的距离（P0 [i]，P1 [i]）

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [79]:
# 考虑2组点P0，P1描述线（2d）和一组点P，如何计算从每个点j（P [j]）到每条线i（P0 [i]，P1 [i]）的距离？

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [99]:
# 考虑一个数组Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
# 如何生成一个数组R = [[1,2,3， 4]，[2,3,4,5]，[3,4,5,6]，...，[11,12,13,14]]
a = np.arange(1,15,dtype=np.uint32)
R = np.lib.stride_tricks.as_strided(a,(11,4),(4,4))
print(R)
a[0] = 100
print(R)
np.lib.stride_tricks.as_strided?

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[100   2   3   4]
 [  2   3   4   5]
 [  3   4   5   6]
 [  4   5   6   7]
 [  5   6   7   8]
 [  6   7   8   9]
 [  7   8   9  10]
 [  8   9  10  11]
 [  9  10  11  12]
 [ 10  11  12  13]
 [ 11  12  13  14]]


#### 82. Compute a matrix rank (★★★)

In [81]:
# 计算一个矩阵的秩

#### 83. How to find the most frequent value in an array?

In [82]:
# 如何找到最常出现的数字
a = np.random.randint(0,10,50)
print(np.bincount(a).argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [83]:
# 从随机10x10矩阵中提取所有连续的3x3块
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
C

array([[[[1, 4, 4],
         [3, 2, 3],
         [0, 1, 0]],

        [[4, 4, 2],
         [2, 3, 2],
         [1, 0, 3]],

        [[4, 2, 1],
         [3, 2, 3],
         [0, 3, 2]],

        [[2, 1, 0],
         [2, 3, 0],
         [3, 2, 0]],

        [[1, 0, 1],
         [3, 0, 2],
         [2, 0, 1]],

        [[0, 1, 0],
         [0, 2, 4],
         [0, 1, 0]],

        [[1, 0, 0],
         [2, 4, 2],
         [1, 0, 2]],

        [[0, 0, 2],
         [4, 2, 4],
         [0, 2, 1]]],


       [[[3, 2, 3],
         [0, 1, 0],
         [0, 1, 4]],

        [[2, 3, 2],
         [1, 0, 3],
         [1, 4, 0]],

        [[3, 2, 3],
         [0, 3, 2],
         [4, 0, 4]],

        [[2, 3, 0],
         [3, 2, 0],
         [0, 4, 4]],

        [[3, 0, 2],
         [2, 0, 1],
         [4, 4, 3]],

        [[0, 2, 4],
         [0, 1, 0],
         [4, 3, 3]],

        [[2, 4, 2],
         [1, 0, 2],
         [3, 3, 4]],

        [[4, 2, 4],
         [0, 2, 1],
         [3, 4, 0]]],


    

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [84]:
# 创建一个二维数组子类，使Z [i，j] == Z [j，i]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [85]:
# 考虑一组形状为（n，n）的p矩阵和一组具有形状（n，1）的p向量。 如何一次计算p矩阵乘积的总和？ （结果有形状（n，1））
# (n, n) * (n, 1) + (n, n) * (n, 1) + ... 
# 可得到次乘法为矩阵乘法
m = np.ones((10,20,20))
v = np.ones((10,20,1))
s = np.tensordot(m, v, axes=[[0,2], [0,1]])
s

array([[200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [86]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [87]:
# 如何使用numpy数组实现生命游戏？

#### 89. How to get the n largest values of an array (★★★)

In [88]:
# 怎样得到第n大的值
a = np.arange(10000)
np.random.shuffle(a)
print(a[np.argsort(a)[-5:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [89]:
# 给定任意数量的向量，构建笛卡尔积（每个项的每个组合）

#### 91. How to create a record array from a regular array? (★★★)

In [90]:
# 如何从常规数组创建记录数组？
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [91]:
# 考虑一个大的向量Z，使用3种不同的方法将Z计算为3的幂
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

4.66 s ± 29.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
82.8 ms ± 5.98 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
304 ms ± 1.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [92]:
# 考虑10x3矩阵，提取具有不等值的行（例如[2,2,3]）
a = np.random.randint(0,2, (10,3))
print(a)
print(np.max(a, axis=-1))
print(np.min(a, axis=-1))

a[np.max(a, axis=-1) != np.min(a, axis=-1),:]

[[0 1 0]
 [0 1 1]
 [0 0 1]
 [1 0 0]
 [0 0 0]
 [1 0 0]
 [0 0 0]
 [0 0 1]
 [1 0 0]
 [1 1 1]]
[1 1 1 1 0 1 0 1 1 1]
[0 0 0 0 0 0 0 0 0 1]


array([[0, 1, 0],
       [0, 1, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [93]:
# 将int的向量转换为矩阵二进制表示？
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [94]:
# 给定一个二维数组，如何提取唯一的行？
# np >= 1.13

a = np.random.randint(0,2,(10,3))
print(a)
np.unique(a, axis=0)

[[1 1 0]
 [1 1 1]
 [0 1 0]
 [0 0 0]
 [0 1 0]
 [1 0 1]
 [0 0 0]
 [0 0 1]
 [1 1 1]
 [1 1 0]]


array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [95]:
# 考虑2个向量A和B，写出einsum等效的inner，outer，sum和mul函数
a = np.random.uniform(0,1,10)
b = np.random.uniform(0,1,10)

# np.einsum('i->',a) # np.sum(a)
# np.einsum('i,i->i',a,b) # a*b

# np.sum(a*b), # np.inner(a,b)内积
# np.einsum('i,i', a,b)

np.einsum('i,j->ij',a,b), np.outer(a,b)


(array([[0.07287634, 0.055945  , 0.00756406, 0.02894254, 0.02552834,
         0.09218051, 0.02785671, 0.09050343, 0.00198037, 0.05736071],
        [0.21329504, 0.16374027, 0.02213856, 0.08470925, 0.07471656,
         0.26979465, 0.08153125, 0.26488617, 0.00579617, 0.16788377],
        [0.18210982, 0.1398003 , 0.01890175, 0.07232417, 0.06379248,
         0.2303488 , 0.06961081, 0.22615797, 0.00494873, 0.143338  ],
        [0.55023686, 0.4224005 , 0.0571108 , 0.21852431, 0.19274619,
         0.69598883, 0.21032603, 0.68332641, 0.01495238, 0.43308949],
        [0.32503046, 0.24951624, 0.03373592, 0.12908452, 0.11385712,
         0.41112762, 0.12424171, 0.4036478 , 0.00883252, 0.25583033],
        [0.05401351, 0.04146457, 0.00560623, 0.02145125, 0.01892076,
         0.06832113, 0.02064647, 0.06707813, 0.00146779, 0.04251385],
        [0.51760504, 0.39735002, 0.05372384, 0.20556472, 0.18131537,
         0.65471318, 0.19785263, 0.64280171, 0.01406563, 0.4074051 ],
        [0.24684667, 0.1894

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [96]:
# 考虑两个矢量（X，Y）描述的路径，如何使用等距样本对其进行采样


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [97]:
# 给定整数n和2D数组X，从X中选择可以解释为具有n度的多项分布的绘制的行，即，仅包含整数并且总和为n的行。

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [98]:
# 计算一维阵列X的平均值的自举95％置信区间（即，重新采样具有替换N次的阵列的元素，计算每个样本的平均值，然后计算均值上的百分位数）。