# Numerical computing with Numpy

## Matplotlib

## Introducing Numpy array

In [1]:
import numpy as np

a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

#### array属性

In [2]:
# 类型， 元素的类型， 维度，  形状，    所占字节数
type(a), a.dtype, a.ndim, a.shape, a.nbytes

(numpy.ndarray, dtype('int64'), 1, (4,), 32)

#### array 操作

In [3]:
# 简单的数学运算
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a + b, [1,2,3,4] + [2,3,4,5]

(array([3, 5, 7, 9]), [1, 2, 3, 4, 2, 3, 4, 5])

In [4]:
a*b, a**b

(array([ 2,  6, 12, 20]), array([   1,    8,   81, 1024]))

In [5]:
# 数学函数
x = np.arange(11.0)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
c = 2*np.pi
c

6.283185307179586

In [7]:
x = x*c
x

array([ 0.        ,  6.28318531, 12.56637061, 18.84955592, 25.13274123,
       31.41592654, 37.69911184, 43.98229715, 50.26548246, 56.54866776,
       62.83185307])

In [8]:
y = np.sin(x)
y

array([ 0.00000000e+00, -2.44929360e-16, -4.89858720e-16, -7.34788079e-16,
       -9.79717439e-16, -1.22464680e-15, -1.46957616e-15, -1.71450552e-15,
       -1.95943488e-15, -2.20436424e-15, -2.44929360e-15])

#### 设置array的值

In [9]:
a[0] = 10.6
a

array([10,  2,  3,  4])

In [10]:
a.dtype

dtype('int64')

In [11]:
a.fill(-4.8)
a

array([-4, -4, -4, -4])

## 多维array

In [12]:
a = np.array([[0,1,2,3],[10,11,12,13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [13]:
type(a), a.dtype, a.ndim, a.shape, a.size, a.nbytes

(numpy.ndarray, dtype('int64'), 2, (2, 4), 8, 64)

In [14]:
a[1,3] = -1
a


array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

In [15]:
# 获得一行的元素
a[1]

array([10, 11, 12, -1])

## 切片与索引

In [16]:
a = np.array([10,11,12, 13,14])
a[1:-2]

array([11, 12])

In [17]:
a[:-2]

array([10, 11, 12])

In [18]:
a[2:]

array([12, 13, 14])

In [19]:
a[::2]

array([10, 12, 14])

In [20]:
a = np.arange(36).reshape((6,6))
# 有具体索引，在输出上少了一维
a[0, 3:5]

array([3, 4])

In [21]:
# 全是切片，则维度不变
a[4:, 4:]

array([[28, 29],
       [34, 35]])

In [22]:
a[:, 2]

array([ 2,  8, 14, 20, 26, 32])

In [23]:
a[2::2, ::2]

array([[12, 14, 16],
       [24, 26, 28]])

### 切片是引用
切片是对原始数组中内存的引用。更改切片中的值也会更改原始数组

In [24]:
a = np.array([0,1,2,3,4])
b = a[2:4]
b

array([2, 3])

In [25]:
b[0] = 10

In [26]:
a

array([ 0,  1, 10,  3,  4])

In [90]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [91]:
b = a[0, :]
b

array([0, 1, 2])

In [92]:
b[0] = 11
b, a

(array([11,  1,  2]), array([[11,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

## 花式索引

In [27]:
a = np.arange(0, 80, 10)

In [28]:
indices = [1,2,-3]
y = a[indices]   # 没用到切片，不会改变a
y[0] = -11
y

array([-11,  20,  50])

In [29]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

#### 用boolean数组索引

In [30]:
mask = np.array([0,1,2,0,0,1,0,0], dtype=bool)

In [31]:
mask

array([False,  True,  True, False, False,  True, False, False])

In [32]:
mask2 = a < 30
mask2

array([ True,  True,  True, False, False, False, False, False])

In [33]:
y = a[mask]
y

array([10, 20, 50])

#### 在2D中的花式索引

In [34]:
a = np.array([[0,1,2,3,4,5],
            [10,11,12,13,14,15],
            [20,21,22,23,24,25],
            [30,31,32,33,34,35],
            [40,41,42,43,44,45],
            [50,51,52,53,54,55]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [35]:
a[[0,1,2,3,4], [1,2,3,4,5]]

array([ 1, 12, 23, 34, 45])

In [36]:
a[3:, [0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [37]:
mask = np.array([1,0,1,0,0,1], dtype=bool)
a[mask,2]

array([ 2, 22, 52])

## Numpy 创建array

In [38]:
a = np.array([0,1.0,2,3])
a.dtype

dtype('float64')

In [39]:
a = np.array([0, 1., 2,3], dtype='float32')
a.dtype

dtype('float32')

In [40]:
a = np.array([0,1,2,3],dtype='uint8')
a.dtype

dtype('uint8')

### 函数建立array

In [41]:
np.arange(4), np.arange(0, np.pi*2, np.pi/4)

(array([0, 1, 2, 3]),
 array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265,
        3.92699082, 4.71238898, 5.49778714]))

In [42]:
np.arange(1.5, 2.1, 0.3), np.arange(1,5,2)

(array([1.5, 1.8, 2.1]), array([1, 3]))

In [43]:
np.ones((2,3), dtype='float32')

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [44]:
np.zeros(3, dtype='int32')

array([0, 0, 0], dtype=int32)

In [45]:
#np.identity生成对角方正
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [47]:
# np.empty空的array
a = np.empty((4,4))
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
a.fill(5.0)
a

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [49]:
# 替换的方法，稍慢
a[:] = 4.0
a

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [50]:
np.linspace(0,1,5)  # 左右包含

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [51]:
np.logspace(0, 1, 5) # 以10为底的指数

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

## array 计算方法

规则一： 做类型匹配

规则二： + - * / exp log 都是元素操作

规则三： 缩减操作应用于整个数组(mean, std, sum)，除非指定某个轴

规则四： 除非显示忽略缺省值，否则缺省值被计算

In [52]:
a = np.array([[1,2,3], [4,5,6]])
np.sum(a), a.sum()

(21, 21)

In [53]:
a.sum(axis=0)

array([5, 7, 9])

In [54]:
a.sum(axis=-1)

array([ 6, 15])

In [55]:
# 其他方法
# sum, prod
# min, max, argmin, argmax
# ptp (max-min)

# mean, std, var
# any , all

In [56]:
a = np.array([2.,3.,0.,1.])
a.min(axis=0), np.min(a, axis=0)

(0.0, 0.0)

In [57]:
# argmin找出最小值的索引
a.argmin(axis=0), np.argmax(a)

(2, 1)

In [58]:
a = np.arange(15).reshape((3,5))
print(a)
np.argmax(a, axis=0), np.argmax(a, axis=-1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


(array([2, 2, 2, 2, 2]), array([4, 4, 4]))

In [59]:
# mean 均值
a = np.arange(1,7).reshape((2,-1))
np.mean(a, axis=0)

array([2.5, 3.5, 4.5])

In [60]:
# 标准差
np.std(a,axis=0)

array([1.5, 1.5, 1.5])

In [61]:
# 方差
np.var(a, axis=0)

array([2.25, 2.25, 2.25])

## 广播计算

不同维度的array可以组合起来计算。

广播较小的数组以匹配较大的数组，不copy数据。

规则一：预处理较小的形状的数组

规则二：尺寸1的重复



In [62]:
a = np.ones((3,5))
b = np.ones((5,))
b = b.reshape(1,5)
b[np.newaxis, :]  # 插入新维度，等价

array([[[1., 1., 1., 1., 1.]]])

In [63]:
c = a + b
c

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [64]:
# 等价于
tmp_b = b.reshape(1,5)
tmp_b_repeat = tmp_b.repeat(3, axis=0)
tmp_b_repeat

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
c = a + tmp_b_repeat
c

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [66]:
# 如图
a = np.array([0,10,20,30]).reshape(-1,1)
b = np.array([0,1,2]) # or reshape(1,-1)
a + b, b.shape

(array([[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]]), (3,))

In [67]:
# 计算时广播
a = np.array([0,10,20,30])
b = np.array([0,1,2])
a[:, np.newaxis] + b # (4,) -> (4,1)

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [68]:
# meshgrid 返回两个向量的组合的坐标。
x, y = np.meshgrid([1,2], [3,4,5])
x

array([[1, 2],
       [1, 2],
       [1, 2]])

In [69]:
y

array([[3, 3],
       [4, 4],
       [5, 5]])

In [70]:
x + y

array([[4, 5],
       [5, 6],
       [6, 7]])

## 通用函数法

In [71]:
# 比较，逻辑，位运算支持两个数组操作, 在array上有特殊功能

# op.reduce()   # 从头到尾做一遍操作op
# y = add.reduce(a)
#   = a[1] + ... + a[n-1]
# op.accumulate() 
# op.outer() 
# op.reduceat()

a = np.array([1,2,3,4])
np.add.reduce(a)

10

In [72]:
a = np.array(['ab', 'cd', 'ef'], dtype='object')
np.sum(a), np.add.reduce(a)

('abcdef', 'abcdef')

In [73]:
a = np.array([1,1,0,1])
np.logical_and.reduce(a)

False

In [74]:
np.logical_or.reduce(a)

True

In [75]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [76]:
np.add.reduce(a)  # 默认axis=0

array([18, 22, 26])

In [77]:
np.add.reduce(a, 1)

array([ 3, 12, 21, 30])

In [78]:
# op.accumulate(a)
# add.accumulate(a)
# = [a[0], a[0]+a[1], ..., a[0]+...+a[n-1]]
a = np.array([1,2,3,4])
np.add.accumulate(a)

array([ 1,  3,  6, 10])

In [79]:
# op.reduceat(a, indices)
# add.reduceat(a, indices)
# = a[ind] + ... + a[ind2-1]

a = np.array([0,10,20,30,40,50])
indices = np.array([1,4])
np.add.reduceat(a, indices)

array([60, 90])

In [80]:
# op.outer()

## array数据结构组织

In [81]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [82]:
a = a.reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [83]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [84]:
a.strides

(24, 8)

In [85]:
a.T.strides

(8, 24)

In [86]:
# flatten 进行了copy
# ravel 和切片一样，同一内存
a = np.array([[0,1],[2,3]])
b = a.flatten()
b

array([0, 1, 2, 3])

In [87]:
b[0] = 10
a

array([[0, 1],
       [2, 3]])

In [88]:
b = a.ravel()
b

array([0, 1, 2, 3])

In [89]:
b[0] = 10
a

array([[10,  1],
       [ 2,  3]])